services:
  db:
    image: postgres:16-alpine
    container_name: myimage
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend_course
    ports:
      - "5432:5432" # local and docker ports
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  db_data:
